const interestList = [
  { value: '3D printing' }, 
  { value: 'Acrobatics' }, 
  { value: 'Acting' }, 
  { value: 'Amateur radio' }, 
  { value: 'Animation' }, 
  { value: 'Aquascaping' }, 
  { value: 'Astronomy' }, 
  { value: 'Baking' }, 
  { value: 'Baton twirling' }, 
  { value: 'Beatboxing' }, 
  { value: 'Blogging' }, 
  { value: 'Building' }, 
  { value: 'Board/tabletop games' }, 
  { value: 'Book discussion clubs' }, 
  { value: 'Book restoration' }, 
  { value: 'Bowling' }, 
  { value: 'Brazilian jiu-jitsu' }, 
  { value: 'Breadmaking' }, 
  { value: 'Cabaret' }, 
  { value: 'Calligraphy' }, 
  { value: 'Candle making' }, 
  { value: 'Car fixing & building' }, 
  { value: 'Card games' }, 
  { value: 'Cheesemaking' }, 
  { value: 'Clothesmaking' }, 
  { value: 'Coffee roasting' }, 
  { value: 'Collecting' }, 
  { value: 'Coloring' }, 
  { value: 'Computer programming' }, 
  { value: 'Confectionery' }, 
  { value: 'Cooking' }, 
  { value: 'Cosplaying' }, 
  { value: 'Couponing' }, 
  { value: 'Craft' }, 
  { value: 'Creative writing' }, 
  { value: 'Crocheting' }, 
  { value: 'Cross-stitch' }, 
  { value: 'Crossword puzzles' }, 
  { value: 'Cryptography' }, 
  { value: 'Cue sports' }, 
  { value: 'Dance' }, 
  { value: 'Diary writing' }, 
  { value: 'Digital arts' }, 
  { value: 'Distro Hopping' }, 
  { value: 'Djing' }, 
  { value: 'Do it yourself' }, 
  { value: 'Drama' }, 
  { value: 'Drawing' }, 
  { value: 'Drink mixing' }, 
  { value: 'Electronics' }, 
  { value: 'Embroidery' }, 
  { value: 'EuroBillTracker' }, 
  { value: 'Experimenting' }, 
  { value: 'Fantasy sports' }, 
  { value: 'Fashion' }, 
  { value: 'Fashion design' }, 
  { value: 'Fishkeeping' }, 
  { value: 'Flower arranging' }, 
  { value: 'Foreign language learning' }, 
  { value: 'Furniture building' }, 
  { value: 'Gaming (tabletop games and role-playing games)' }, 
  { value: 'Genealogy' }, 
  { value: 'Gingerbread house making' }, 
  { value: 'Glassblowing' }, 
  { value: 'Graphic design' }, 
  { value: 'Gunsmithing' }, 
  { value: 'Herp keeping' }, 
  { value: 'Home improvement' }, 
  { value: 'Homebrewing' }, 
  { value: 'Hula hooping' }, 
  { value: 'Hydroponics' }, 
  { value: 'Ice skating' }, 
  { value: 'Jewelry making' }, 
  { value: 'Jigsaw puzzles' }, 
  { value: 'Juggling' }, 
  { value: 'Karaoke' }, 
  { value: 'Karate' }, 
  { value: 'Kendama' }, 
  { value: 'Knife making' }, 
  { value: 'Knitting' }, 
  { value: 'Knot tying' }, 
  { value: 'Kombucha brewing' }, 
  { value: 'Lace making' }, 
  { value: 'Lapidary' }, 
  { value: 'Leather crafting' }, 
  { value: 'Lego building' }, 
  { value: 'Lock picking' }, 
  { value: 'Listening to music' }, 
  { value: 'Listening to podcasts' }, 
  { value: 'Machining' }, 
  { value: 'Macrame' }, 
  { value: 'Magic' }, 
  { value: 'Makeup' }, 
  { value: 'Metalworking' }, 
  { value: 'Model building' }, 
  { value: 'Model engineering' }, 
  { value: 'Nail Art' }, 
  { value: 'Needlepoint' }, 
  { value: 'Origami' }, 
  { value: 'Painting' }, 
  { value: 'Pet adoption & fostering' }, 
  { value: 'Philately' }, 
  { value: 'Photography' }, 
  { value: 'Practical jokes' }, 
  { value: 'Pressed flower craft' }, 
  { value: 'Playing musical instruments' }, 
  { value: 'Poi' }, 
  { value: 'Pottery' }, 
  { value: 'Puzzles' }, 
  { value: 'Quilling' }, 
  { value: 'Quilting' }, 
  { value: 'Quizzes' }, 
  { value: 'Rail transport modeling' }, 
  { value: 'Rapping' }, 
  { value: 'Reading' }, 
  { value: 'Refinishing' }, 
  { value: 'Robot combat' }, 
  { value: 'Rubik\'s Cube' }, 
  { value: 'Scrapbooking' }, 
  { value: 'Sculpting' }, 
  { value: 'Sewing' }, 
  { value: 'Shoemaking' }, 
  { value: 'Singing' }, 
  { value: 'Sketching' }, 
  { value: 'Soapmaking' }, 
  { value: 'Social media' }, 
  { value: 'Stand-up comedy' }, 
  { value: 'Stamp collecting' }, 
  { value: 'Table tennis' }, 
  { value: 'Taxidermy' }, 
  { value: 'Thrifting' }, 
  { value: 'Video editing' }, 
  { value: 'Video game developing' }, 
  { value: 'Video gaming' }, 
  { value: 'Watching movies' }, 
  { value: 'Watching television' }, 
  { value: 'Weaving' }, 
  { value: 'Weight training' }, 
  { value: 'Welding' }, 
  { value: 'Whittling' }, 
  { value: 'Wikipedia Editing' }, 
  { value: 'Winemaking' }, 
  { value: 'Wood carving' }, 
  { value: 'Woodworking' }, 
  { value: 'Worldbuilding' }, 
  { value: 'Writing' }, 
  { value: 'Word searches' }, 
  { value: 'Yo-yoing' }, 
  { value: 'Yoga' }, 
  { value: 'Air sports' }, 
  { value: 'Archery' }, 
  { value: 'Astronomy' }, 
  { value: 'Backpacking' }, 
  { value: 'BASE jumping' }, 
  { value: 'Baseball' }, 
  { value: 'Basketball' }, 
  { value: 'Beekeeping' }, 
  { value: 'Bird watching' }, 
  { value: 'Blacksmithing' }, 
  { value: 'BMX' }, 
  { value: 'Board sports' }, 
  { value: 'Bodybuilding' }, 
  { value: 'Butterfly watching' }, 
  { value: 'Camping' }, 
  { value: 'Canoeing' }, 
  { value: 'Canyoning' }, 
  { value: 'Caving' }, 
  { value: 'Composting' }, 
  { value: 'Cycling' }, 
  { value: 'Dowsing' }, 
  { value: 'Driving' }, 
  { value: 'Fishing' }, 
  { value: 'Flag football' }, 
  { value: 'Flower growing' }, 
  { value: 'Flying' }, 
  { value: 'Flying disc' }, 
  { value: 'Foraging' }, 
  { value: 'Freestyle football' }, 
  { value: 'Gardening' }, 
  { value: 'Geocaching' }, 
  { value: 'Ghost hunting' }, 
  { value: 'Gold prospecting' }, 
  { value: 'Graffiti' }, 
  { value: 'Handball' }, 
  { value: 'Herbalism' }, 
  { value: 'Herping' }, 
  { value: 'High-power rocketry' }, 
  { value: 'Hiking' }, 
  { value: 'Hobby horsing' }, 
  { value: 'Hooping' }, 
  { value: 'Horseback riding' }, 
  { value: 'Hunting' }, 
  { value: 'Inline skating' }, 
  { value: 'Jogging' }, 
  { value: 'Kayaking' }, 
  { value: 'Kite flying' }, 
  { value: 'Kitesurfing' }, 
  { value: 'Lacrosse' }, 
  { value: 'LARPing' }, 
  { value: 'Letterboxing' }, 
  { value: 'Longboarding' }, 
  { value: 'Martial arts' }, 
  { value: 'Metal detecting' }, 
  { value: 'Meteorology' }, 
  { value: 'Motor sports' }, 
  { value: 'Mountain biking' }, 
  { value: 'Mountaineering' }, 
  { value: 'Mushroom hunting/mycology' }, 
  { value: 'Netball' }, 
  { value: 'Nordic skating' }, 
  { value: 'Orienteering' }, 
  { value: 'Paintball' }, 
  { value: 'Parkour' }, 
  { value: 'Photography' }, 
  { value: 'Podcast hosting' }, 
  { value: 'Polo' }, 
  { value: 'Powerlifting' }, 
  { value: 'Rafting' }, 
  { value: 'Rappelling' }, 
  { value: 'Road biking' }, 
  { value: 'Rock climbing' }, 
  { value: 'Roller skating' }, 
  { value: 'Rugby' }, 
  { value: 'Running' }, 
  { value: 'Sailing' }, 
  { value: 'Sand art' }, 
  { value: 'Scouting' }, 
  { value: 'Scuba diving' }, 
  { value: 'Sculling or rowing' }, 
  { value: 'Shooting' }, 
  { value: 'Shopping' }, 
  { value: 'Skateboarding' }, 
  { value: 'Skiing' }, 
  { value: 'Skimboarding' }, 
  { value: 'Skydiving' }, 
  { value: 'Slacklining' }, 
  { value: 'Snowboarding' }, 
  { value: 'Soccer' }, 
  { value: 'Stone skipping' }, 
  { value: 'Sun bathing' }, 
  { value: 'Surfing' }, 
  { value: 'Survivalism' }, 
  { value: 'Swimming' }, 
  { value: 'Taekwondo' }, 
  { value: 'Tai chi' }, 
  { value: 'Topiary' }, 
  { value: 'Travel' }, 
  { value: 'Urban exploration' }, 
  { value: 'Vacation' }, 
  { value: 'Vegetable farming' }, 
  { value: 'Vehicle restoration' }, 
  { value: 'Walking' }, 
  { value: 'Water sports' }
]

export default interestList
