const majorList = [
  { value: 'Accountancy' }, 
  { value: 'Aerospace Engineering' }, 
  { value: 'African American Studies' }, 
  { value: 'Anthropology' }, 
  { value: 'Applied Physics' }, 
  { value: 'Art' }, 
  { value: 'Art History' }, 
  { value: 'Asian American Studies' }, 
  { value: 'Biochemistry and Molecular Biology' }, 
  { value: 'Biological Sciences' }, 
  { value: 'Biology/Education' }, 
  { value: 'Biomedical and Translational Science' }, 
  { value: 'Biomedical Engineering' }, 
  { value: 'Biomedical Engineering: Premedical' }, 
  { value: 'Biomedical Sciences2' }, 
  { value: 'Biotechnology Management' }, 
  { value: 'Business Administration' }, 
  { value: 'Business Analytics' }, 
  { value: 'Business Economics' }, 
  { value: 'Business Information Management' }, 
  { value: 'Chemical and Biomolecular Engineering' }, 
  { value: 'Chemical Engineering' }, 
  { value: 'Chemistry' }, 
  { value: 'Chicano/Latino Studies' }, 
  { value: 'Chinese Studies' }, 
  { value: 'Civil and Environmental Engineering' }, 
  { value: 'Civil Engineering' }, 
  { value: 'Classics' }, 
  { value: 'Cognitive Neuroscience' }, 
  { value: 'Cognitive Sciences' }, 
  { value: 'Comparative Literature' }, 
  { value: 'Computational Science' }, 
  { value: 'Computer Engineering' }, 
  { value: 'Computer Game Science' }, 
  { value: 'Computer Science' }, 
  { value: 'Computer Science and Engineering' }, 
  { value: 'Conservation and Restoration Science' }, 
  { value: 'Criminology, Law and Society' }, 
  { value: 'Culture and Theory' }, 
  { value: 'Dance' }, 
  { value: 'Data Science' }, 
  { value: 'Developmental and Cell Biology' }, 
  { value: 'Drama' }, 
  { value: 'Drama and Theatre' }, 
  { value: 'Earth System Science' }, 
  { value: 'East Asian Cultures' }, 
  { value: 'East Asian Studies' }, 
  { value: 'Ecology and Evolutionary Biology' }, 
  { value: 'Economics' }, 
  { value: 'EducationCredential Programs' }, 
  { value: 'Education' }, 
  { value: 'Education Sciences' }, 
  { value: 'Electrical and Computer Engineering' }, 
  { value: 'Electrical Engineering' }, 
  { value: 'Elementary and Secondary Education' }, 
  { value: 'Embedded and Cyber-Physical Systems' }, 
  { value: 'Engineering' }, 
  { value: 'Engineering Management' }, 
  { value: 'English' }, 
  { value: 'Environmental Engineering' }, 
  { value: 'Environmental Health Sciences' }, 
  { value: 'Environmental Science' }, 
  { value: 'Environmental Science and Policy' }, 
  { value: 'Epidemiology2' }, 
  { value: 'European Studies' }, 
  { value: 'European Thought and Culture' }, 
  { value: 'Exercise Sciences' }, 
  { value: 'Film and Media Studies' }, 
  { value: 'Finance' }, 
  { value: 'French' }, 
  { value: 'Gender and Sexuality Studies' }, 
  { value: 'Genetic Counseling' }, 
  { value: 'Genetics' }, 
  { value: 'German' }, 
  { value: 'German Studies' }, 
  { value: 'Global Cultures' }, 
  { value: 'Global Middle East Studies' }, 
  { value: 'History' }, 
  { value: 'Human Biology' }, 
  { value: 'Human Computer Interaction and Design' }, 
  { value: 'Informatics' }, 
  { value: 'Information and Computer Science' }, 
  { value: 'Innovation and Entrepreneurship' }, 
  { value: 'Integrated Composition, Improvisation, and Technology' }, 
  { value: 'International Studies' }, 
  { value: 'Japanese Language and Literature' }, 
  { value: 'Korean Literature and Culture' }, 
  { value: 'Language Science' }, 
  { value: 'Law' }, 
  { value: 'Legal and Forensic Psychology' }, 
  { value: 'Literary Journalism' }, 
  { value: 'Management' }, 
  { value: 'Materials Science and Engineering' }, 
  { value: 'Materials Science and Engineering' }, 
  { value: 'Mathematical, Computational, and Systems Biology' }, 
  { value: 'Mathematics' }, 
  { value: 'Mechanical and Aerospace Engineering' }, 
  { value: 'Mechanical Engineering' }, 
  { value: 'Medicine' }, 
  { value: 'Microbiology and Immunology' }, 
  { value: 'Music' }, 
  { value: 'Music Theatre' }, 
  { value: 'Networked Systems' }, 
  { value: 'Neurobiology' }, 
  { value: 'Nursing' }, 
  { value: 'Nursing Science' }, 
  { value: 'Pharmaceutical Sciences' }, 
  { value: 'Pharmacological Sciences' }, 
  { value: 'Pharmacology' }, 
  { value: 'Philosophy' }, 
  { value: 'Philosophy, Political Science, and Economics' }, 
  { value: 'Physics' }, 
  { value: 'Political Science' }, 
  { value: 'Psychological Science' }, 
  { value: 'Psychology' }, 
  { value: 'Public Health' }, 
  { value: 'Public Health Policy' }, 
  { value: 'Public Health Sciences' }, 
  { value: 'Public Policy' }, 
  { value: 'Quantitative Economics' }, 
  { value: 'Religious Studies' }, 
  { value: 'Social Ecology' }, 
  { value: 'Social Policy and Public Service' }, 
  { value: 'Social Science' }, 
  { value: 'Sociology' }, 
  { value: 'Software Engineering' }, 
  { value: 'Spanish' }, 
  { value: 'Statistics' }, 
  { value: 'Transportation Science' }, 
  { value: 'Urban and Environmental Planning and Policy' }, 
  { value: 'Urban and Regional Planning' }, 
  { value: 'Urban Studies' }, 
  { value: 'Visual Studies'}
]

export default majorList